name: Check new release
on:
  # schedule:
  #   # all 12 hours
  #   - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
      - uses: actions/setup-node@v1
      - name: Check update
        run: |
          echo current_version=`npm view deno-bin version` >> $GITHUB_ENV
          echo latest_version=`deno -V | awk '{print $2}'` >> $GITHUB_ENV

      - name: Show versions
        run: |
          echo latest_version=${{ env.latest_version }}
          echo current_version=${{ env.current_version }}

      - name: Bump
        if: env.latest_version != env.current_version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx json-edit-cli set -f './versions.json' -k 'DENO_VERSION' -v '${{ env.latest_version }}'
          npx json-edit-cli set -f './versions.json' -k 'TARGET_PACKAGE_SUFFIX' -v ''

      - name: build new version
        run: |
          deno task builder-ci

      - name: publish new version
        working-directory: dist
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
          npm publish

      - name: Push changes back
        if: env.latest_version != env.current_version
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.latest_version }}
          message: "${{ env.latest_version }}"
