name: CI
on: [push, pull_request]

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
      - uses: actions/setup-node@v1
      - run: deno task builder-ci
      - run: npm install
        working-directory: dist
      - run: npx deno --version
        working-directory: dist
